### ISSUE TITLE
meshlab is based on git sources not on file

### ISSUE THREAD

**Issue by Stunkymonkey** [bartoszek/AUR-meshlab#1]
currently it is cloning the master branch and then it compiles everything.

For `-git` packages this is perfectly fine.

But for non-git packages it is advised to use specific commits or packets. Currently the `PKGBUILD` does not contain any if this. Therefore compiling this today can lead to a different result then tomorrow. This i not wanted, when compiling for non-git packages. It should provide always the same output.

Two Options:
- download [source](https://github.com/cnr-isti-vclab/meshlab/releases/download/Meshlab-2020.09/MeshLab2020.09-linux.tar.gz) directly(prefered)
- stick to latest commit (https://github.com/cnr-isti-vclab/meshlab/commit/a595226b8b02505afbf9fd4ffbccbd6011046ae6)

**Comment by bartoszek** [comment]
Yep, when switching from `qmake` to `cmake` dcbdc95c I was renormalizing this PKGBUILD against https://github.com/bartoszek/AUR-meshlab-git and forgot to put `git#fragment` again in source link 😞
