### ISSUE TITLE
updating with development packets

### ISSUE THREAD

**Issue by Stunkymonkey** [bartoszek/AUR-meshlab#2]
`yay` has also the option to update development packets, which is meant to be used for `-git`
it can be executed by:
```
yay -Syu --devel
```
because `meshlab` is still based on git-sources (and not on e.g. `zip`/`.tar.gz` files) it thinks, that there are updates for `meshlab` if some new commits are done at the repo.

currently I know, that the `vcglib`is also needed an also used via git-sources. So changing this now would need hard commit hashes. Or You could wait and also include the new release comming next month: https://github.com/cnr-isti-vclab/vcglib/issues/86

**Comment by Stunkymonkey** [comment]
with the new release this is easily possible

**Comment by bartoszek** [comment]
> because meshlab is still based on git-sources (and not on e.g. zip/.tar.gz files) it thinks, that there are updates for meshlab if some new commits are done at the repo.

I've took quick looksy at `yay` code and it looks like it should skip packages that `vcs source` has `fragment` specified 💡
https://github.com/Jguer/yay/blob/1db50882e9c44b940237ad5c1f42366d35c3c6de/pkg/vcs/vcs.go#L146-L149
Edit: Yep, `meshlab` is not indexed in `~/.cache/yay/vcs.json` so it should be ignored by `yay -Su --devel` (tested in `arch-nspawn` container)

**Comment by Stunkymonkey** [comment]
let me test this. If the problem persists, i will reply. Otherwise I would close the issue.

**Comment by Stunkymonkey** [comment]
i can agree that it should work, but sadly it does not.
```
$ yay -Syu --devel
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> Flagged Out Of Date AUR Packages:  spotify
:: 1 Packages to upgrade.
1  devel/meshlab  2020.12-2 -> latest-commit
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
```

what about downloading the [sources](https://github.com/cnr-isti-vclab/meshlab/releases/download/Meshlab-2020.12/MeshLab2020.12-linux.tar.gz) instead of using git.

**Comment by bartoszek** [comment]
Strange, what version of `yay` you're using (`{yay:10.1.1}` )

About using github archive tarball as source, I would rather not to... for maintenance coherence across vsc <> nonvsc version of the package (e.g: `aur/meshlab{,-git}` vs. `aur/luxcorerender{,-git}` which is a jumbled mess in contrast :feelsgood: ) it's is easier this way (also creating patches is easy as calling `git diff > $$$.patch` 🚧 

But if there's no other way I'm willing to take that as a solution.

**Comment by Stunkymonkey** [comment]
```
$ yay --version
yay v10.1.1 - libalpm v12.0.2
```
maybe there is another solution. But i am not experienced enough

**Comment by Stunkymonkey** [comment]
i recently switched to NixOS, so it is no longer of much interest for me. Feel free to fix or close it.
