### ISSUE TITLE
Is there a reason why this depends on openssl-1.0?

### ISSUE THREAD

**Issue by frankspace** [bartoszek/AUR-meshlab#4]
I've tested compiling this in a chroot with the current, i.e., 3.0.7-2, version of openssl installed, and it seems to compile and run just fine.  I have no clue what it could possibly need ssl for beyond checking for updates (which it does seem to do successfully), but I haven't been able to discover any reason why it needs an obsolete and end-of-life'd version of openssl.  May I respectfully suggest considering dropping the "-1.0" requirement for openssl?

**Comment by bartoszek** [comment]
Gave me a sec, this old shit is there for `nexus` sake.
